// <auto-generated />
using Gighub.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gighub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191017191528_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview1.19506.2");

            modelBuilder.Entity("Gighub.Models.ErrorViewModel", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.ToTable("ErrorViews");
                });
#pragma warning restore 612, 618
        }
    }
}
